title: CLIJ2
logo: /images/clij2_logo.png
description: CLIJ2
show_downloads: false
google_analytics:
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-redirect-from
